[package]
name = "flowpay-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
flowpay-agent = { path = "../agent" }
flowpay-chains = { path = "../chains" }
flowpay-claims = { path = "../claims" }
flowpay-domain = { path = "../domain" }
flowpay-evm = { path = "../evm" }
flowpay-messaging = { path = "../messaging" }
flowpay-payments = { path = "../payments" }
flowpay-persistence = { path = "../persistence" }
flowpay-policy = { path = "../policy" }
flowpay-recovery = { path = "../recovery" }
flowpay-signer = { path = "../signer" }
flowpay-webhooks = { path = "../webhooks" }
futures-util.workspace = true
hex.workspace = true
hmac.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true
url.workspace = true

[lints]
workspace = true
