[package]
name = "flowpay-chains"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
flowpay-domain = { path = "../domain" }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
