export type Chain = "base" | "bsc";
export type PaymentStatus = "CREATED"|"WAITING"|"DETECTED"|"CONFIRMING"|"PARTIALLY_PAID"|"OVERPAID"|"WRONG_ASSET"|"WRONG_CHAIN_CLAIMED"|"CONFIRMED"|"SETTLING"|"COMPLETED"|"EXPIRED"|"FAILED"|"CLAIM_PENDING"|"RECOVERY_AVAILABLE"|"RECOVERY_PENDING"|"RECOVERED"|"ESCALATED"|"CANCELLED";
export interface Payment { id:string; address:string; amount:string; amount_atomic:string; asset:string; chain:Chain; status:PaymentStatus; expires_at:string; reference?:string|null; merchant_name?:string|null; checkout_url:string }
export interface CreatePaymentInput { amount:string; asset:string; chain:Chain; reference?:string; expires_in_seconds?:number; overpayment_policy?:"ACCEPT_AND_RECORD"|"REQUIRE_REVIEW"|"REJECT_SETTLEMENT" }
export interface CreateClaimInput { payment_id:string; transaction_hash?:string; actual_chain?:Chain; actual_asset?:string; originating_wallet?:string; recovery_destination:string; explanation:string }
export interface FlowPayOptions { apiKey:string; baseUrl?:string; fetch?:typeof globalThis.fetch }
export class FlowPayError extends Error { constructor(public status:number, public code:string, message:string, public requestId?:string){super(message);this.name="FlowPayError";} }

export class FlowPay {
  readonly payments:{create:(i:CreatePaymentInput,o?:{idempotencyKey?:string})=>Promise<Payment>;get:(id:string)=>Promise<Payment>;cancel:(id:string)=>Promise<unknown>;deposits:(id:string)=>Promise<unknown>};
  readonly claims:{create:(i:CreateClaimInput,o?:{idempotencyKey?:string})=>Promise<any>;get:(id:string)=>Promise<any>;evidence:(id:string,input:Record<string,unknown>)=>Promise<any>;authorize:(id:string,signature:string)=>Promise<any>;fund:(id:string)=>Promise<any>;approve:(id:string)=>Promise<any>};
  readonly webhooks:{list:()=>Promise<any>;create:(url:string,events?:string[])=>Promise<any>;test:()=>Promise<any>};
  private readonly apiKey:string; private readonly baseUrl:string; private readonly fetcher:typeof globalThis.fetch;
  constructor(options:FlowPayOptions){if(!options.apiKey)throw new Error("FlowPay apiKey is required");this.apiKey=options.apiKey;this.baseUrl=(options.baseUrl??"http://127.0.0.1:8080").replace(/\/$/,"");this.fetcher=options.fetch??globalThis.fetch;
    this.payments={create:(i,o)=>this.request("POST","/v1/payments",i,o?.idempotencyKey??crypto.randomUUID()),get:id=>this.request("GET",`/v1/payments/${encodeURIComponent(id)}`),cancel:id=>this.request("POST",`/v1/payments/${encodeURIComponent(id)}/cancel`),deposits:id=>this.request("GET",`/v1/payments/${encodeURIComponent(id)}/deposits`)};
    this.claims={create:(i,o)=>this.request("POST","/v1/claims",i,o?.idempotencyKey??crypto.randomUUID()),get:id=>this.request("GET",`/v1/claims/${encodeURIComponent(id)}`),evidence:(id,input)=>this.request("POST",`/v1/claims/${encodeURIComponent(id)}/evidence`,input),authorize:(id,signature)=>this.request("POST",`/v1/claims/${encodeURIComponent(id)}/authorize`,{signature}),fund:id=>this.request("POST",`/v1/claims/${encodeURIComponent(id)}/fund`),approve:id=>this.request("POST",`/v1/claims/${encodeURIComponent(id)}/approve`)};
    this.webhooks={list:()=>this.request("GET","/v1/webhooks"),create:(url,events)=>this.request("POST","/v1/webhooks",{url,events}),test:()=>this.request("POST","/v1/webhooks/test")};
  }
  private async request<T>(method:string,path:string,body?:unknown,idempotencyKey?:string):Promise<T>{const headers:Record<string,string>={"x-flowpay-api-key":this.apiKey,"accept":"application/json"};if(body!==undefined)headers["content-type"]="application/json";if(idempotencyKey)headers["idempotency-key"]=idempotencyKey;const response=await this.fetcher(this.baseUrl+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let parsed:any={};try{parsed=text?JSON.parse(text):{};}catch{parsed={message:text};}if(!response.ok){const e=parsed?.error??{};throw new FlowPayError(response.status,e.code??"http_error",e.message??`FlowPay request failed (${response.status})`,e.request_id);}return parsed as T;}
}

export function verifyWebhookSignature(rawBody:string|Uint8Array,signatureHeader:string,secret:string,options:{nowSeconds?:number;toleranceSeconds?:number}={}):Promise<boolean>{
  const parts=Object.fromEntries(signatureHeader.split(",").map(p=>p.split("=",2) as [string,string]));const ts=Number(parts.t);if(!Number.isFinite(ts)||!parts.v1)return Promise.resolve(false);const now=options.nowSeconds??Math.floor(Date.now()/1000);if(Math.abs(now-ts)>(options.toleranceSeconds??300))return Promise.resolve(false);const bytes=typeof rawBody==="string"?new TextEncoder().encode(rawBody):rawBody;const prefix=new TextEncoder().encode(`${ts}.`);const input=new Uint8Array(prefix.length+bytes.length);input.set(prefix);input.set(bytes,prefix.length);return crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]).then(async key=>{const mac=new Uint8Array(await crypto.subtle.sign("HMAC",key,input));const expected=Array.from(mac,b=>b.toString(16).padStart(2,"0")).join("");if(expected.length!==parts.v1.length)return false;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^parts.v1.charCodeAt(i);return diff===0;});
}
