[package]
name = "flowpay-payments"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
flowpay-domain = { path = "../domain" }
serde.workspace = true
sha3.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
