"use client";
import {FormEvent,useState} from "react";
import {RefreshData} from "../components/RefreshData";
type Endpoint={id:string;url:string;events:string[];enabled:boolean};
export function WebhookSettings({initialEndpoints,unavailable}:{initialEndpoints:Endpoint[];unavailable:boolean}){
 const [endpoints,setEndpoints]=useState(initialEndpoints);const [url,setUrl]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [secret,setSecret]=useState("");const [copied,setCopied]=useState(false);
 async function request(action:string,payload:unknown){const response=await fetch("/api/webhooks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload as object})});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message??"Webhook settings could not be saved.");return body;}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setMessage("");setSecret("");setCopied(false);const value=url.trim();let target:URL;try{target=new URL(value);}catch{setError("Enter a valid HTTPS endpoint URL.");return;}if(target.protocol!=="https:"||target.username||target.password||target.hash){setError("Use an HTTPS URL without credentials or a fragment.");return;}if(endpoints.some(endpoint=>endpoint.url===value)){setError("This endpoint is already connected.");return;}setBusy(true);try{const body=await request("create",{url:value});setEndpoints(previous=>[body,...previous]);setSecret(body.signing_secret??"");setUrl("");setMessage("Webhook endpoint connected. Store the signing secret before leaving this page.");}catch(e){setError(e instanceof Error?e.message:"Unable to save endpoint");}finally{setBusy(false);}}
 async function test(){setBusy(true);setError("");setMessage("");try{await request("test",{});setMessage("Test event queued for your enabled endpoints. Check your receiver for delivery.");}catch(e){setError(e instanceof Error?e.message:"Unable to queue test event");}finally{setBusy(false);}}
 return <section id="webhooks" className="workspace-card settings-webhooks"><header className="workspace-section-heading"><div><h2>Webhook endpoints</h2><p>Send signed payment events directly to your application.</p></div></header><div className="settings-webhook-body"><form onSubmit={save}><label htmlFor="webhook-url">Endpoint URL</label><p>Your server should accept HTTPS POST requests and return a successful response.</p><div className="webhook-input-row"><input id="webhook-url" type="url" required placeholder="https://your-app.com/webhooks/flowpay" value={url} onChange={e=>setUrl(e.target.value)} disabled={busy}/><button className="workspace-primary" disabled={busy}>{busy?"Saving...":"Connect endpoint"}</button></div><small>Receives all payment and recovery events. Deliveries are signed and retried automatically.</small></form>{error&&<p className="settings-error" role="alert">{error}</p>}{message&&<p className="settings-success" role="status">{message}</p>}{secret&&<div className="webhook-secret"><strong>Signing secret - shown once</strong><p>Keep this in your server configuration to verify webhook signatures.</p><code>{secret}</code><button className="workspace-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(secret);setCopied(true);}catch{setError("Copy the signing secret manually.");}}}>{copied?"Copied":"Copy secret"}</button></div>}
 {unavailable&&endpoints.length===0?<div className="workspace-empty"><h3>Connected endpoints could not be loaded</h3><p>Try again to retrieve your saved webhook settings.</p><RefreshData/></div>:<div className="webhook-endpoints">{endpoints.length?endpoints.map(endpoint=><div className="webhook-endpoint" key={endpoint.id}><div><strong>{endpoint.url}</strong><small>{endpoint.events?.length?endpoint.events.join(", "):"All events"}</small></div><span className={`workspace-status ${endpoint.enabled?"success":"neutral"}`}>{endpoint.enabled?"Connected":"Disabled"}</span></div>):<p className="webhook-none">No endpoints connected yet. Add your webhook URL above to get started.</p>}</div>}
 <div className="webhook-test"><div><strong>Check your integration</strong><p>Queue a test event for your enabled endpoints.</p></div><button type="button" className="workspace-secondary" onClick={test} disabled={busy||!endpoints.some(e=>e.enabled)}>Send test event</button></div><a className="settings-doc-link" href="/docs#webhooks">Read the webhook integration guide</a></div></section>;
}
