import {api} from "../../lib/api";
import {requireMerchant} from "../../lib/session";
import {moneyFromStableBalances,networkLabel,statusTone} from "../../lib/format";
import {ArrowRightIcon,LinkIcon,PaymentIcon,WalletIcon,ShieldIcon,CodeIcon,SettingsIcon} from "../components/Icons";
import "./dashboard.scss";
import {RefreshData} from "../components/RefreshData";
const completed=new Set(["COMPLETED","RECOVERED","CONFIRMED"]);
const closed=new Set(["COMPLETED","RECOVERED","CONFIRMED","FAILED","EXPIRED","CANCELLED"]);
export default async function Dashboard(){
 const merchant=await requireMerchant();
 const [overview,result]=await Promise.allSettled([api("/v1/merchant/overview",{signal:AbortSignal.timeout(10000)}),api("/v1/payments?limit=100",{signal:AbortSignal.timeout(10000)})]);
 const payments:any[]=result.status==="fulfilled"?result.value?.data??[]:[];
 const stable=overview.status==="fulfilled"?(overview.value?.balances??[]).filter((b:any)=>["USDC","USDT"].includes(String(b.symbol).toUpperCase())):[];
 const balanceAvailable=stable.length>0&&stable.every((b:any)=>!b.error&&b.amount_atomic!==undefined);
 let balance:string|null=null;if(balanceAvailable){try{balance=moneyFromStableBalances(stable);}catch{}}
 const recent=payments.slice(0,5);const settled=payments.filter(p=>completed.has(p.status));
 const totals=new Map<string,number>();for(const p of settled){const amount=Number(p.amount);if(Number.isFinite(amount))totals.set(p.asset,(totals.get(p.asset)??0)+amount);}
 const counts=overview.status==="fulfilled"?overview.value?.payments:null;
 const active=payments.filter(p=>!closed.has(p.status));
 const success=payments.length?Math.round(settled.length/payments.length*100):0;
 return <div className="workspace-page dashboard-v2">
  <header className="dashboard-heading"><div><span className="workspace-eyebrow">PAYMENT OPERATIONS</span><h1>Overview</h1><p><span className="dashboard-business-name">{merchant.business_name}</span><span className="heading-divider"/><span>Everything you need to keep payments moving.</span></p></div><div className="dashboard-heading-actions"><RefreshData/><a className="workspace-primary" href="/payments/new"><LinkIcon/>Create payment</a></div></header>
  <div className="dashboard-summary-grid">
   <section className="dashboard-balance"><div className="balance-top"><span><WalletIcon/>Settlement balance</span><span className="balance-tag">USDC + USDT</span></div><div className="balance-value">{balance??"\u2014"}</div><p>{balance?"Stablecoins held in your settlement wallet":"Balance could not be retrieved"}</p><div className="balance-networks">{balanceAvailable?stable.map((b:any)=><span key={`${b.chain}-${b.symbol}`}>{networkLabel(b.chain)}</span>):<span>Your wallet stays under your control</span>}</div><footer><div><small>SETTLEMENT WALLET</small><code title={merchant.settlement_address??undefined}>{merchant.settlement_address?`${merchant.settlement_address.slice(0,8)}...${merchant.settlement_address.slice(-6)}`:"Wallet not connected"}</code></div><a href="/settings">Manage wallet<ArrowRightIcon/></a></footer></section>
   <div className="dashboard-counts"><section className="workspace-card dashboard-count"><span><PaymentIcon/>Total payments</span><strong>{counts?.total??(result.status==="fulfilled"?payments.length:"\u2014")}</strong><small>{counts?"All payment requests":"Latest 100 payment requests"}</small><a href="/history" aria-label="View payment history"><ArrowRightIcon/></a></section><section className="workspace-card dashboard-count"><span><ShieldIcon/>Completed</span><strong>{counts?.completed??(result.status==="fulfilled"?settled.length:"\u2014")}</strong><small>Payments successfully completed</small><a href="/history" aria-label="View completed payments"><ArrowRightIcon/></a></section></div>
  </div>
  <div className="dashboard-detail-grid"><section className="workspace-card dashboard-activity"><header className="workspace-section-heading"><div><h2>Payment activity</h2><p>Your most recent payment requests.</p></div><a href="/history">View all<ArrowRightIcon/></a></header>
  {result.status==="rejected"?<div className="workspace-empty" role="status"><PaymentIcon/><h3>Activity could not be loaded</h3><p>Refresh to retrieve your payment requests.</p><RefreshData/></div>:recent.length===0?<div className="workspace-empty dashboard-first-payment"><div className="first-payment-icon"><LinkIcon/></div><h3>Ready for your first payment</h3><p>Create a link, share it, and follow every payment here.</p><a className="workspace-primary" href="/payments/new">Create payment link<ArrowRightIcon/></a></div>:<div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>Payment</th><th>Status</th><th className="align-right">Amount</th></tr></thead><tbody>{recent.map(p=><tr key={p.id}><td><a href={`/payments/${encodeURIComponent(p.id)}`}><strong>{p.reference||"Payment request"}</strong><small>{networkLabel(p.chain)} <span aria-hidden="true">/</span> {p.id.slice(-8)}</small></a></td><td><span className={`workspace-status ${statusTone(p.status)}`}>{String(p.status).replaceAll("_"," ").toLowerCase()}</span></td><td className="align-right"><strong>{p.amount}</strong><small>{p.asset}</small></td></tr>)}</tbody></table></div>}
  <footer className="dashboard-activity-footer"><span>{result.status==="fulfilled"?`${active.length} active requests in the latest 100`:"Payment data is temporarily unavailable"}</span><a href="/payments">Manage payments<ArrowRightIcon/></a></footer></section>
  <aside className="dashboard-insights"><section className="workspace-card dashboard-health"><div className="insight-heading"><span>Completion overview</span><PaymentIcon/></div><div className="completion-stat"><strong>{result.status==="fulfilled"?`${success}%`:"\u2014"}</strong><span>of recent requests<br/>completed</span></div><div className="completion-track"><i style={{width:`${success}%`}}/></div><div className="completion-breakdown"><span><i/>{settled.length} completed</span><span><i/>{active.length} active</span></div><p>Based on the latest {payments.length} requests.</p></section><section className="workspace-card dashboard-volume"><span className="workspace-eyebrow">COMPLETED VOLUME</span>{totals.size?[...totals].map(([asset,amount])=><div className="volume-asset" key={asset}><span>{asset}</span><strong>{amount.toLocaleString("en-US",{maximumFractionDigits:6})}</strong></div>):<p>Completed volume will appear here after your first payment.</p>}<small>Latest 100 requests. Each asset is counted separately.</small></section></aside></div>
  <div className="dashboard-shortcuts"><a href="/payments/new"><span className="shortcut-icon"><LinkIcon/></span><div><strong>Payment links</strong><small>A checkout your customers can open anywhere.</small></div><ArrowRightIcon/></a><a href="/developers"><span className="shortcut-icon"><CodeIcon/></span><div><strong>Build with FlowPay</strong><small>Connect your app with an API key.</small></div><ArrowRightIcon/></a><a href="/settings#webhooks"><span className="shortcut-icon"><SettingsIcon/></span><div><strong>Stay in sync</strong><small>Get payment events at your webhook endpoint.</small></div><ArrowRightIcon/></a></div>
 </div>;
}
