import {CodeBlock,Icon} from "./docs/DocsUi";
import styles from "./page.module.scss";

export const metadata={title:"FlowPay — Payments that fit your product",description:"Create crypto payment links, verify on-chain receipts, and integrate payments into your product with FlowPay."};

const features=[
  {icon:"link",title:"One link. A clear checkout.",copy:"Give customers a payment request with the amount, asset, and network already set.",number:"01"},
  {icon:"check",title:"Receipts you can work with.",copy:"Follow each payment from detection to completion with verified on-chain evidence.",number:"02"},
  {icon:"layers",title:"Keep your wallet in the flow.",copy:"Connect your settlement wallet and keep control of where your funds arrive.",number:"03"},
];

export default function LandingPage(){return <div className={styles.site}>
  <a className={styles.skip} href="#main">Skip to content</a>
  <header className={styles.header}><a className={styles.brand} href="/"><img src="/assets/flowpay-mark.svg" alt=""/>FlowPay</a><nav aria-label="Primary navigation"><a href="#product">Product</a><a href="#developers">Developers</a><a href="/docs">Documentation <Icon name="external"/></a></nav><div className={styles.headerActions}><a href="/login">Sign in</a><a className={styles.primary} href="/signup">Get started <Icon/></a></div></header>
  <main id="main">
    <section className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}><i/>PAYMENTS, IN YOUR FLOW</span><h1>A better way<br/>to move <em>money.</em></h1><p>Crypto payments that feel like part of your product. Create a link, share it, and settle to your wallet.</p><div className={styles.actions}><a className={styles.primary} href="/signup">Start building <Icon/></a><a className={styles.secondary} href="/docs">Read the docs <Icon name="book"/></a></div><div className={styles.heroNote}><span><Icon name="check"/>Your settlement wallet</span><span><Icon name="check"/>Verified on-chain</span></div></div>
      <div className={styles.heroVisual} aria-label="Illustration of a FlowPay payment request"><div className={styles.visualGrid}/><span className={styles.orbitOne}/><span className={styles.orbitTwo}/><span className={styles.visualLabel}>A SMALL LINK. A COMPLETE PAYMENT FLOW.</span><div className={styles.paymentCard}><div className={styles.cardTop}><img src="/assets/flowpay-mark.svg" alt=""/><span>FlowPay checkout</span><span className={styles.example}>Example</span></div><div className={styles.cardAmount}><span>Payment request</span><strong>20.00 <small>USDC</small></strong><p>Ready when you are.</p></div><div className={styles.cardDetails}><span>Network<strong>Ethereum Sepolia</strong></span><span>Asset<strong><i/>USDC</strong></span></div><div className={styles.cardAddress}><Icon name="layers"/><div><span>Send to the request address</span><code>0x7a2f...9c41</code></div><Icon name="copy"/></div><div className={styles.cardStatus}><span><i/>Waiting for payment</span><Icon/></div><div className={styles.cardFoot}><Icon name="check"/>On-chain verification, built in.</div></div><div className={styles.floatingNote}><span><Icon name="check"/></span><div><strong>From request to receipt.</strong><p>Every step, connected.</p></div></div><span className={styles.visualBottom}>CREATE → SHARE → CONFIRM</span></div>
    </section>
    <div className={styles.networks}><span>ONE CONNECTED PAYMENT LAYER</span><div><img src="/assets/ethereum.svg" alt=""/>Ethereum</div><div><img src="/assets/base.svg" alt=""/>Base</div><div><img src="/assets/arbitrum.svg" alt=""/>Arbitrum</div><div><img src="/assets/usdc.svg" alt=""/>USDC</div><a href="/docs#payments">Explore payment flows <Icon/></a></div>
    <section className={styles.product} id="product"><div className={styles.sectionHead}><span className={styles.eyebrow}>LESS FRICTION. MORE FLOW.</span><h2>Everything a payment needs.<br/><em>Nothing in your way.</em></h2><p>One connected path from the first request to the final receipt. Designed for the way you build.</p></div><div className={styles.features}>{features.map(feature=><article key={feature.number}><div><Icon name={feature.icon}/><span>{feature.number}</span></div><h3>{feature.title}</h3><p>{feature.copy}</p></article>)}</div></section>
    <section className={styles.developers} id="developers"><div><span className={styles.eyebrow}>MADE FOR YOUR STACK</span><h2>Your idea.<br/>Your interface.<br/><em>Our payment rails.</em></h2><p>Start in the terminal. Connect your AI client. Build directly on the API. The same payment flow, wherever you work.</p><a className={styles.textLink} href="/docs">Explore the developer guide <Icon/></a></div><div className={styles.developerPanel}><div className={styles.panelTitle}><span><i/>THE SHORTEST PATH TO A PAYMENT</span><Icon name="terminal"/></div><CodeBlock label="Your terminal" code={"flowpay init\nflowpay request 20 usdc eth\nflowpay payment wait PAYMENT_ID"}/><div className={styles.developerLinks}><a href="/docs#quickstart"><Icon name="terminal"/><strong>CLI</strong><span>From the terminal</span><Icon/></a><a href="/docs#mcp"><Icon name="layers"/><strong>MCP</strong><span>For your AI client</span><Icon/></a><a href="/docs#api"><Icon name="code"/><strong>API</strong><span>Inside your product</span><Icon/></a></div></div></section>
    <section className={styles.details}><div className={styles.sectionHead}><span className={styles.eyebrow}>BUILT FOR WHAT COMES NEXT</span><h2>The details make<br/><em>the difference.</em></h2></div><div><article><span>01 / VISIBILITY</span><h3>A payment should never be a mystery.</h3><p>Track payment states and receive signed webhook events so your application knows what happened and when.</p><a href="/docs#webhooks">Explore webhooks <Icon/></a></article><article><span>02 / RECOVERY</span><h3>Make room for the unexpected.</h3><p>Wrong asset or wrong network? Evidence-backed recovery workflows help you investigate and review the next step.</p><a href="/claims">Explore recovery <Icon/></a></article></div></section>
    <section className={styles.cta}><div><span className={styles.eyebrow}>LET'S BUILD SOMETHING</span><h2>Your next payment<br/>starts <em>here.</em></h2><p>Bring your product. We'll bring the payment flow.</p></div><div><a className={styles.primary} href="/signup">Get started with FlowPay <Icon/></a><a href="/docs">Or start with the documentation <Icon name="external"/></a></div></section>
  </main>
  <footer className={styles.footer}><div><a className={styles.brand} href="/"><img src="/assets/flowpay-mark.svg" alt=""/>FlowPay</a><p>Payments that fit your product.</p></div><nav aria-label="Footer navigation"><div><strong>Build</strong><a href="/docs">Documentation</a><a href="/docs#api">Payment API</a><a href="/docs#mcp">MCP connections</a></div><div><strong>FlowPay</strong><a href="/login">Sign in</a><a href="/signup">Create an account</a><a href="https://github.com/gowithflowpay/flowpay">GitHub <Icon name="external"/></a></div></nav><div className={styles.footerBottom}><span>© 2026 FlowPay</span><span>Built for the way you build.</span></div></footer>
</div>;}
