import {api} from "../../../lib/api";
import {short,statusTone} from "../../../lib/format";
import {ArrowLeftIcon,BotIcon,CheckIcon,ShieldIcon} from "../../components/Icons";
async function approve(id:string){"use server";await api(`/v1/claims/${id}/approve`,{method:"POST"});}
async function fund(id:string){"use server";await api(`/v1/claims/${id}/fund`,{method:"POST"});}
export default async function ClaimDetail({params}:{params:Promise<{id:string}>}){
  const {id}=await params;
  if(!id||id==="undefined")return <><a href="/claims" className="back-link"><ArrowLeftIcon/>Back to claims</a><div className="page-head"><div><div className="eyebrow">Claim investigation</div><h1>Invalid claim ID</h1><p>The claim ID is missing or invalid.</p></div></div></>;
  try{
  const c=await api(`/v1/claims/${id}`),rec=c?.recovery;
  const runs=c?.agent?.runs??[],latestRun=runs.at(-1);
  const status=c?.status??"UNKNOWN";
  return <><a href="/claims" className="back-link"><ArrowLeftIcon/>Back to claims</a><div className="page-head"><div><div className="eyebrow">Claim investigation</div><h1>{status.replaceAll("_"," ")}</h1><p className="mono">{c?.id??id}</p></div><div className="actions">{rec?.policy_decision==="NEEDS_FUNDING"?<form action={fund.bind(null,id)}><button className="btn secondary">Fund test gas</button></form>:null}{status==="APPROVAL_PENDING"?<form action={approve.bind(null,id)}><button className="btn primary"><CheckIcon/>Approve recovery</button></form>:null}</div></div>
<div className="agent-banner"><div className="bot"><BotIcon/></div><div><strong>{latestRun?.mode==="MODEL_TOOL_USE"?"Model-driven investigator":"Deterministic investigation"}</strong><span>{latestRun?.mode==="MODEL_TOOL_USE"?`${latestRun?.model_provider??"model"} · ${latestRun?.model_name??"configured model"} selected read-only tools; policy and execution remain deterministic.`:"No model controlled this run. This mode is used only as a safe fallback/baseline."}</span></div></div>
<div className="two-col"><section className="panel detail-panel"><h2>Expected vs actual</h2><div className="kv"><div>Payment</div><div className="mono">{c?.payment_id??"—"}</div><div>Expected</div><div>{c?.expected_asset??"—"} on {c?.expected_chain??"—"}</div><div>Claimed actual</div><div>{c?.actual_asset??"?"} on {c?.actual_chain??"?"}</div><div>Transaction</div><div className="mono">{c?.transaction_hash??"—"}</div><div>Originating wallet</div><div className="mono">{c?.originating_wallet??"—"}</div><div>Recovery destination</div><div className="mono">{c?.recovery_destination??"—"}</div></div></section><section className="panel detail-panel"><h2>Customer explanation</h2><p>{c?.explanation??"—"}</p><div className="danger-note">Screenshots and descriptions are investigation inputs only. Financial facts must be independently verified on-chain.</div></section></div>
<div className="two-col section-gap"><section className="panel detail-panel"><h2>Investigation timeline</h2><div className="timeline">{(c?.agent?.tool_calls??[]).map((t:any,i:number)=><div className="timeline-step" key={`${t?.sequence}-${i}`}><span className="timeline-dot"/><strong>{t?.tool}</strong><span>{t?.status}{t?.error_class?` · ${t.error_class}`:""}</span>{t?.output?<pre className="tool-box">{JSON.stringify(t.output,null,2)}</pre>:null}</div>)}</div>{(c?.agent?.tool_calls??[]).length===0?<div className="empty-note">Investigation has not produced a tool trajectory yet.</div>:null}</section><section className="panel detail-panel"><h2>Recovery plan</h2>{!rec?<div className="empty-note">No recovery plan has passed the investigation boundary.</div>:<><div className="kv"><div>Policy decision</div><div><span className={`status ${statusTone(rec?.policy_decision)}`}>{rec?.policy_decision??"—"}</span></div><div>Simulation</div><div><span className={`status ${rec?.simulation_status==="SUCCEEDED"?"success":"warn"}`}>{rec?.simulation_status??"—"}</span></div><div>Amount atomic</div><div className="mono">{rec?.amount_atomic??"—"}</div><div>Deploy receiver</div><div>{rec?.receiver_deployment_required?"Required":"Already deployed"}</div><div>Estimated gas</div><div>{rec?.estimated_gas??"—"}</div><div>Approval</div><div>{rec?.approval_status??"—"}</div><div>Recovery tx</div><div className="mono">{rec?.recovery_tx??"—"}</div><div>Plan hash</div><div className="mono">{short(rec?.plan_hash,12,10)}</div></div><div className="security-row"><div className="security-icon"><ShieldIcon/></div><div><strong>Execution boundary</strong><span>Plan hash → simulation → human approval → restricted signer → receipt/balance verification.</span></div></div></>}</section></div>
<section className="panel detail-panel section-gap"><h2>Audit-safe decisions</h2><div className="timeline">{(c?.agent?.decisions??[]).map((d:any,i:number)=><div className="timeline-step" key={`${d?.sequence}-${i}`}><span className="timeline-dot"/><strong>{d?.rationale??"—"}</strong><span>{d?.verification??"—"}</span></div>)}</div></section></>;
  }catch(error){return <><a href="/claims" className="back-link"><ArrowLeftIcon/>Back to claims</a><div className="page-head"><div><div className="eyebrow">Claim investigation</div><h1>Error loading claim</h1><p>{error instanceof Error?error.message:"Failed to load claim details."}</p></div></div></>;}
}