"use client";
import {FormEvent,useMemo,useState} from "react";
import {CheckIcon,CopyIcon,KeyIcon,MoreIcon,PlusIcon,ShieldIcon} from "../components/Icons";

type DateValue=string|number|null;
type Environment="live"|"test";
type Key={id:string;name:string;prefix:string;created_at?:DateValue;last_used_at?:DateValue;revoked:boolean};
type Created={publicKey:string;secretKey:string;credential:string};
const timestamp=(value?:DateValue)=>{if(value===null||value===undefined||value==="")return null;const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed};
const date=(value?:DateValue)=>{const parsed=timestamp(value);return parsed?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(parsed):"Unknown date"};
const relative=(value?:DateValue)=>{const parsed=timestamp(value);if(!parsed)return "Never used";const hours=Math.max(0,Math.floor((Date.now()-parsed.getTime())/3600000));return hours<1?"Used just now":hours<24?`Used ${hours}h ago`:`Used ${Math.floor(hours/24)}d ago`};

export function ApiKeysPanel({initialKeys}:{initialKeys:Key[]}){
  const [keys,setKeys]=useState(initialKeys),[filter,setFilter]=useState<"all"|Environment>("all"),[modal,setModal]=useState(false),[name,setName]=useState("Production key"),[environment,setEnvironment]=useState<Environment>("live"),[created,setCreated]=useState<Created|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState("");
  const visible=useMemo(()=>keys.filter(key=>filter==="all"||key.prefix.includes(`_${filter}_`)),[keys,filter]);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/api-keys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim(),environment,permissions:["full_access"]})});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message??body?.error??"Could not create key");const prefix=body.public_key??String(body.api_key).split(".")[0],secret=body.secret_key??String(body.api_key).split(".")[1];setCreated({publicKey:prefix,secretKey:secret,credential:body.api_key});setKeys(current=>[{id:body.id,name:name.trim(),prefix,created_at:Date.now(),last_used_at:null,revoked:false},...current]);setFilter(environment)}catch(value){setError(value instanceof Error?value.message:"Could not create key")}finally{setBusy(false)}}
  async function copy(value:string,field:string){await navigator.clipboard.writeText(value);setCopied(field);window.setTimeout(()=>setCopied(""),1500)}
  async function revoke(id:string){const response=await fetch(`/api/api-keys?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(response.ok)setKeys(current=>current.map(key=>key.id===id?{...key,revoked:true}:key))}
  function open(){setModal(true);setCreated(null);setError("")}
  function close(){setModal(false);setCreated(null);setError("");setName("Production key");setEnvironment("live")}
  return <>
    <section className="api-compact-shell">
      <div className="page-head api-page-head"><div><h1>API Keys</h1><p>Manage keys used to access the FlowPay API.</p></div><button className="btn primary generate-key" onClick={open}><PlusIcon/>Create API key</button></div>
      <div className="environment-tabs" aria-label="Filter API keys"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All keys <span>{keys.length}</span></button><button className={filter==="live"?"active":""} onClick={()=>setFilter("live")}><i className="live-dot"/>Live mode</button><button className={filter==="test"?"active":""} onClick={()=>setFilter("test")}><i className="test-dot"/>Test mode</button></div>
      <section className="key-list">{visible.map(key=>{const env:keyof {live:1,test:1}=key.prefix.includes("_test_")?"test":"live";return <article className="key-row" key={key.id}><div className="key-main"><div className="key-title"><strong>{key.name}</strong><span className={`key-env ${env}`}>{env==="live"?"Live":"Test"}</span></div><div className="key-value"><code>{key.prefix}_••••••••••••••••••••</code><button onClick={()=>void copy(key.prefix,"prefix-"+key.id)} aria-label="Copy key identifier">{copied==="prefix-"+key.id?<CheckIcon/>:<CopyIcon/>}</button></div><p>Created {date(key.created_at)} <b>·</b> {relative(key.last_used_at)}{env==="test"?<><b>·</b> Test environment</>:null}</p></div><div className="key-side"><span className={`status ${key.revoked?"bad":"success"}`}>{key.revoked?"Revoked":"Active"}</span><button className="key-menu" onClick={()=>!key.revoked&&void revoke(key.id)} title={key.revoked?"Key revoked":"Revoke key"}><MoreIcon/></button></div></article>})}{visible.length===0?<div className="api-empty"><KeyIcon/><h3>No {filter==="all"?"API":filter} keys</h3><p>Create a key for this environment when you are ready.</p><button className="btn primary" onClick={open}><PlusIcon/>Create API key</button></div>:null}</section>
      <div className="api-security"><ShieldIcon/><div><strong>Keep your API keys secure</strong><span>Secret keys are shown only once when created.</span></div></div>
    </section>
    {modal?<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)close()}}><section className="key-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={close} aria-label="Close">×</button>{created?<><div className="modal-icon success"><CheckIcon/></div><h2>Save your secret key</h2><p>This is the only time FlowPay will show the complete credential.</p><SecretRow label="API key" value={created.publicKey} copied={copied==="public"} onCopy={()=>void copy(created.publicKey,"public")}/><SecretRow label="Secret key" value={created.secretKey} copied={copied==="secret"} onCopy={()=>void copy(created.secretKey,"secret")}/><button className="copy-secret" onClick={()=>void copy(created.credential,"credential")}>{copied==="credential"?<CheckIcon/>:<CopyIcon/>}{copied==="credential"?"Credential copied":"Copy complete credential"}</button><div className="one-time-warning"><ShieldIcon/>Save this key now. You won’t be able to see it again.</div><button className="btn primary modal-submit" onClick={close}>I’ve saved the key</button></>:<form onSubmit={event=>void create(event)}><div className="modal-icon"><KeyIcon/></div><h2>Create API key</h2><p>Create a secure credential for your application.</p><label className="modal-field"><span>Key name</span><input value={name} onChange={event=>setName(event.target.value)} maxLength={80} required autoFocus/></label><fieldset className="modal-choice"><legend>Environment</legend><label className={environment==="live"?"selected":""}><input type="radio" checked={environment==="live"} onChange={()=>setEnvironment("live")}/><i className="live-dot"/><span><strong>Live</strong><small>Production payments</small></span></label><label className={environment==="test"?"selected":""}><input type="radio" checked={environment==="test"} onChange={()=>setEnvironment("test")}/><i className="test-dot"/><span><strong>Test</strong><small>Sandbox integration</small></span></label></fieldset><label className="modal-field"><span>Permissions</span><select defaultValue="full_access"><option value="full_access">Full API access</option></select><small>Can create payments and manage webhooks.</small></label>{error?<div className="form-error">{error}</div>:null}<div className="modal-actions"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn primary" disabled={busy||!name.trim()}>{busy?"Creating…":"Create key"}</button></div></form>}</section></div>:null}
  </>
}

function SecretRow({label,value,copied,onCopy}:{label:string,value:string,copied:boolean,onCopy:()=>void}){return <div className="secret-row"><label>{label}</label><div><code>{value}</code><button onClick={onCopy}>{copied?<CheckIcon/>:<CopyIcon/>}{copied?"Copied":"Copy"}</button></div></div>}
