[package]
name = "flowpay-signer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
alloy-primitives.workspace = true
async-trait.workspace = true
flowpay-chains = { path = "../chains" }
flowpay-domain = { path = "../domain" }
ethers-core.workspace = true
ethers-signers.workspace = true
hex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
