import {CodeBlock,DocsNavigation,Icon,TableOfContents} from "./DocsUi";
import styles from "./page.module.scss";

export const metadata={title:"Documentation | FlowPay",description:"A practical guide to crypto payments. Get started with the FlowPay CLI, connect an MCP client, and integrate the payment API."};

function Heading({number,title}:{number:string;title:string}){return <div className={styles.sectionTitle}><span>{number}</span><h2>{title}</h2></div>;}

const apiCommand=`curl https://api.pixuno.xyz/v1/payments \\
  -H "Content-Type: application/json" \\
  -H "x-flowpay-api-key: $FLOWPAY_API_KEY" \\
  -H "Idempotency-Key: order-1042" \\
  -d '{
    "amount": "20",
    "asset": "USDC",
    "chain": "ethereum_sepolia",
    "reference": "order-1042"
  }'`;
const webhookCommand=`curl https://api.pixuno.xyz/v1/webhooks \\
  -H "Content-Type: application/json" \\
  -H "x-flowpay-api-key: $FLOWPAY_API_KEY" \\
  -d '{
    "url": "https://your-app.com/webhooks/flowpay",
    "events": ["payment.completed", "payment.failed"]
  }'`;

export default function Documentation(){return <div className={styles.docs}>
  <a className={styles.skipLink} href="#docs-content">Skip to content</a>
  <header className={styles.header}><a className={styles.brand} href="/"><img src="/assets/flowpay-mark.svg" alt=""/>FlowPay<span><span className={styles.fullLabel}>Documentation</span><span className={styles.shortLabel}>Docs</span></span></a><nav aria-label="Site navigation"><a href="/">Website</a><a href="https://github.com/gowithflowpay/flowpay">GitHub <Icon name="external"/></a><a className={styles.signIn} href="/login">Sign in <Icon/></a></nav></header>
  <div className={styles.layout}><DocsNavigation/><main className={styles.content} id="docs-content">
    <div className={styles.breadcrumb}><Icon name="book"/>Documentation<span>/</span>Overview</div>
    <div className={styles.intro}><span className={styles.eyebrow}><i/>THE DEVELOPER GUIDE</span><h1>Build your<br/><em>payment flow.</em></h1><p>From your first payment link to a complete integration. Everything you need to build with FlowPay, in one place.</p><div className={styles.badges}><span><i/>Ethereum Sepolia testnet</span><span>Node.js 20+</span><span>Device-key sign-in</span></div></div>
    <div className={styles.quickLinks}>{[["quickstart","terminal","Start in the terminal","A few commands. Your first payment request.","CLI quickstart"],["mcp","layers","Connect your AI client","Bring payment tools to your agent workspace.","MCP guide"],["api","code","Build it your way","Your interface. FlowPay under the hood.","API reference"]].map(([id,icon,title,copy,label])=><a href={`#${id}`} key={id}><Icon name={icon} className={styles.cardIcon}/><strong>{title}<Icon/></strong><p>{copy}</p><span>{label}<Icon/></span></a>)}</div>
    <div className={styles.readingNote}><span>YOUR FIRST INTEGRATION</span><p>Install. Sign in. Create a payment.</p><span>01 — 03 <Icon/></span></div>
    <section id="quickstart" className={styles.section}><Heading number="01" title="Install the CLI"/><p>Start with the FlowPay command line. The public package includes the Node.js SDK, so you can move from terminal to code when you are ready.</p><CodeBlock label="Terminal" code={"npm install -g https://api.pixuno.xyz/downloads/flowpay-cli.tgz\nflowpay --help"}/><div className={styles.callout}><Icon name="check"/><div><strong>Before you start</strong><p>Use Node.js 20 or later and an EVM settlement wallet. Your wallet address starts with <code>0x</code>.</p></div></div></section>
    <section id="account" className={styles.section}><Heading number="02" title="Make yourself at home"/><p>Create an account from your terminal. The CLI wizard collects your business name, recovery email and settlement wallet, then creates a device key and signs you in automatically. There is no password, email code or browser approval.</p><CodeBlock label="Registration" code="flowpay register"/><div className={styles.tableWrap}><table><thead><tr><th>Field</th><th>What you need</th></tr></thead><tbody><tr><td>Business name</td><td>The name your customers recognize.</td></tr><tr><td>Device key</td><td>Generated locally and used automatically for sign-in.</td></tr><tr><td>Email address</td><td>Your recovery contact. Recording it does not verify ownership.</td></tr><tr><td>Settlement wallet</td><td>Your EVM wallet address, starting with <code>0x</code>.</td></tr></tbody></table></div><h3>Already registered?</h3><p>Sign in automatically using the key on the device where you registered.</p><CodeBlock label="Device sign-in" code="flowpay login"/><p className={styles.caption}>Run <code>flowpay init</code> for first-time setup. Existing browser accounts may use <code>flowpay device</code>. <code>flowpay logout</code> removes the session and keeps your device key for future sign-in.</p></section>
    <section id="payments" className={styles.section}><Heading number="03" title="Your first payment request"/><p>Request 20 USDC on Ethereum Sepolia. The CLI returns a payment ID, deposit address, and checkout URL to share with your customer.</p><CodeBlock label="Create a payment" code="flowpay request 20 usdc eth"/><div className={styles.paymentSteps}>{[["01","Create","Choose an amount, asset, and network."],["02","Share","Send the checkout URL to the payer."],["03","Confirm","Wait for the verified payment receipt."]].map(([number,title,copy])=><div key={title}><span>{number}</span><strong>{title}</strong><p>{copy}</p></div>)}</div><div className={styles.callout}><Icon name="layers"/><div><strong>A note on networks</strong><p>The CLI alias <code>eth</code> refers to Ethereum Sepolia testnet. Use the asset and network displayed in the payment request.</p></div></div><h3>Keep the command in your workflow</h3><div className={styles.tableWrap}><table><thead><tr><th>Option</th><th>What it does</th></tr></thead><tbody><tr><td><code>--no-open</code></td><td>Creates the request without opening a browser.</td></tr><tr><td><code>--no-wait</code></td><td>Returns the request without waiting for payment.</td></tr><tr><td><code>--json</code></td><td>Returns structured output for your application.</td></tr></tbody></table></div><p>Use the returned payment ID to pick up monitoring at any time.</p><CodeBlock label="Resume monitoring" code="flowpay payment wait PAYMENT_ID"/></section>
    <section id="agents" className={styles.section}><Heading number="04" title="Give your agent payment tools"/><p>Create requests, share checkout URLs, and monitor payment state with predictable JSON output. The payer sends the transfer from its wallet.</p><CodeBlock label="Agent commands" code={"flowpay request 20 usdc eth --json\nflowpay payment status PAYMENT_ID --json\nflowpay payment wait PAYMENT_ID --json"}/><div className={styles.callout}><Icon name="code"/><div><strong>One configuration per agent</strong><p>Set <code>FLOWPAY_CONFIG_DIR</code> to isolate each agent's approved credentials. Keep credentials in configuration, outside prompts and logs.</p></div></div></section>
    <section id="mcp" className={styles.section}><Heading number="05" title="Connect your AI workspace"/><p>Use FlowPay from a compatible remote MCP client. Add the hosted connector URL, then authorize the payment tools through your FlowPay account.</p><CodeBlock label="MCP server URL" language="url" code="https://mcp.pixuno.xyz/mcp"/><ol className={styles.instructions}><li><strong>Add the connector</strong><p>Paste the server URL into your client's remote MCP settings.</p></li><li><strong>Sign in to FlowPay</strong><p>Follow the authorization page and enter your email sign-in code.</p></li><li><strong>Review the permissions</strong><p>Approve scoped access through OAuth with PKCE. Manage connected apps in <a href="/developers">Developers</a>.</p></li></ol><p className={styles.caption}>Remote connector support and setup vary by client and plan.</p></section>
    <section id="api" className={styles.section}><Heading number="06" title="Your product. Our payment API."/><p>Create payment requests from your backend. Authenticate with your merchant API key and send an idempotency key to prevent duplicate requests.</p><div className={styles.endpoint}><span>POST</span><code>/v1/payments</code><span>Create a payment</span></div><CodeBlock label="Create with the API" code={apiCommand}/><p>The response includes <code>id</code>, <code>address</code>, <code>checkout_url</code>, and <code>status</code>. Share the checkout URL with your customer.</p><div className={styles.endpoint}><span className={styles.getMethod}>GET</span><code>/v1/payments/:id</code><span>Read payment state</span></div><CodeBlock label="Check payment status" code={'curl https://api.pixuno.xyz/v1/payments/PAYMENT_ID \\\n  -H "x-flowpay-api-key: $FLOWPAY_API_KEY"'}/><p className={styles.caption}>Create and store merchant credentials in <a href="/developers">Developers</a>. API keys belong in your server environment.</p></section>
    <section id="webhooks" className={styles.section}><Heading number="07" title="Let payment events come to you"/><p>Register an HTTPS endpoint to receive signed payment lifecycle events. Subscribe to the events your application needs.</p><CodeBlock label="Register a webhook" code={webhookCommand}/><div className={styles.tableWrap}><table><thead><tr><th>Event</th><th>When to use it</th></tr></thead><tbody>{[["payment.detected","A transfer has been detected."],["payment.confirmed","The payment has reached confirmation."],["payment.completed","The payment workflow is complete."],["payment.failed","The payment workflow failed."]].map(([event,description])=><tr key={event}><td><code>{event}</code></td><td>{description}</td></tr>)}</tbody></table></div><p>Verify the signature before handling an event and process repeated deliveries idempotently. Manage endpoints in <a href="/webhooks">Webhooks</a>.</p></section>
    <div className={styles.resources}><a href="https://github.com/gowithflowpay/flowpay/tree/main/flowpay/apps/cli"><Icon name="terminal"/><div><strong>CLI reference</strong><p>Commands, options, and examples.</p></div><Icon name="external"/></a><a href="https://github.com/gowithflowpay/flowpay/blob/main/flowpay/apps/mcp/README.md"><Icon name="layers"/><div><strong>MCP reference</strong><p>Remote connectors and local setup.</p></div><Icon name="external"/></a></div>
    <footer className={styles.footer}><span>Built with FlowPay.</span><a href="https://github.com/gowithflowpay/flowpay">Improve these docs <Icon name="external"/></a><a href="#docs-content">Back to top <span aria-hidden="true">↑</span></a></footer>
  </main><TableOfContents/></div>
</div>;}
