import {CodeBlock,DocsNavigation} from "./DocsUi";
import styles from "./page.module.scss";

export const metadata={title:"Documentation | FlowPay",description:"Install the CLI, request crypto payments, connect MCP clients and build workflows for agents."};

export default function Documentation(){
  return <div className={styles.docs}>
    <header className={styles.header}><a className={styles.brand} href="/"><img src="/assets/flowpay-mark.svg" alt=""/>FlowPay<span>Docs</span></a><nav aria-label="Site navigation"><a href="/">Website</a><a href="https://github.com/gowithflowpay/flowpay">GitHub &nearr;</a><a className={styles.signIn} href="/login">Sign in &rarr;</a></nav></header>
    <div className={styles.layout}>
      <DocsNavigation/>
      <main className={styles.content}>
        <div className={styles.breadcrumb}>Get started <span>/</span> Overview</div>
        <div className={styles.intro}><span className={styles.eyebrow}>FLOWPAY DOCUMENTATION</span><h1>Build your payment flow.</h1><p>Accept crypto from your terminal, connect your AI client, or build directly on the API. Start with the tools that fit your workflow.</p><div className={styles.badges}><span><i/>Ethereum Sepolia</span><span>Node.js 20+</span><span>Email OTP</span></div></div>
        <div className={styles.quickLinks}><a href="#quickstart"><span className={styles.cardIcon} aria-hidden="true">&gt;_</span><strong>Command line <span>&nearr;</span></strong><p>Install, sign in, request a payment.</p></a><a href="#mcp"><span className={styles.cardIcon} aria-hidden="true">◇</span><strong>MCP connections <span>&nearr;</span></strong><p>Connect ChatGPT or Claude.</p></a><a href="#agents"><span className={styles.cardIcon} aria-hidden="true">⇄</span><strong>Agent workflows <span>&nearr;</span></strong><p>Create and monitor with JSON.</p></a></div>
        <section id="quickstart" className={styles.section}><div className={styles.sectionTitle}><span>01</span><h2>Install the CLI</h2></div><p>Run this command in your terminal. The public package includes the FlowPay SDK.</p><CodeBlock label="Terminal" code={"npm install -g https://api.pixuno.xyz/downloads/flowpay-cli.tgz\nflowpay --help"}/><div className={styles.callout}><span aria-hidden="true">i</span><p><strong>Before you start</strong>Install Node.js 20 or later. Your settlement wallet must support EVM addresses.</p></div></section>
        <section id="account" className={styles.section}><div className={styles.sectionTitle}><span>02</span><h2>Create an account</h2></div><p>The CLI guides you through registration, then sends a code to your email. Enter that code to verify your account.</p><CodeBlock label="Registration" code="flowpay register"/><div className={styles.tableWrap}><table><thead><tr><th>Registration field</th><th>What to enter</th></tr></thead><tbody><tr><td>Business name</td><td>The name customers recognize.</td></tr><tr><td>Contact name</td><td>Your name.</td></tr><tr><td>Email</td><td>The address used for sign-in codes.</td></tr><tr><td>Settlement wallet</td><td>Your EVM wallet address, starting with <code>0x</code>.</td></tr></tbody></table></div><h3>Already have an account?</h3><p>Sign in with your email and one-time code. Existing merchants can also approve a CLI device from the dashboard.</p><CodeBlock label="Email sign-in" code="flowpay login"/><p className={styles.caption}>Use <code>flowpay init</code> for browser device approval. Use <code>flowpay logout</code> to remove local credentials.</p></section>
        <section id="payments" className={styles.section}><div className={styles.sectionTitle}><span>03</span><h2>Request your first payment</h2></div><p>Create a request for 20 USDC. The terminal prints the wallet address and checkout URL you can share.</p><CodeBlock label="Ethereum Sepolia" code="flowpay request 20 usdc eth"/><div className={styles.paymentSteps}><div><span>1</span><strong>Create</strong><p>Set the amount, asset and network.</p></div><div><span>2</span><strong>Share</strong><p>Send the address or checkout URL.</p></div><div><span>3</span><strong>Confirm</strong><p>Wait for the verified receipt.</p></div></div><p>Interactive requests open HTTPS checkout in your browser. The CLI waits and displays a confirmation when the backend verifies payment.</p><div className={styles.callout}><span aria-hidden="true">i</span><p><strong>Currently on testnet</strong>The <code>eth</code> alias means Ethereum Sepolia. Send the requested test asset on the exact network shown in checkout.</p></div><h3>Control how the command runs</h3><div className={styles.tableWrap}><table><thead><tr><th>Option</th><th>Behavior</th></tr></thead><tbody><tr><td><code>--no-open</code></td><td>Keep the browser closed.</td></tr><tr><td><code>--no-wait</code></td><td>Print the request and return immediately.</td></tr><tr><td><code>--json</code></td><td>Return structured JSON for automation.</td></tr></tbody></table></div><p>Replace <code>PAYMENT_ID</code> with the ID returned by your request to resume monitoring.</p><CodeBlock label="Resume monitoring" code="flowpay payment wait PAYMENT_ID"/></section>
        <section id="agents" className={styles.section}><div className={styles.sectionTitle}><span>04</span><h2>Build agent workflows</h2></div><p>Agents can create requests, exchange checkout URLs or addresses, and monitor payment state. JSON output keeps these workflows machine-readable.</p><CodeBlock label="Agent commands" code={"flowpay request 20 usdc eth --json\nflowpay payment status PAYMENT_ID --json\nflowpay payment wait PAYMENT_ID --json"}/><p>Use <code>FLOWPAY_CONFIG_DIR</code> to give each agent its own approved configuration. Credentials stay outside prompts and logs. Creating a request does not broadcast a transfer; the payer submits it through its wallet.</p></section>
        <section id="mcp" className={styles.section}><div className={styles.sectionTitle}><span>05</span><h2>Connect your AI client</h2></div><p>Add the hosted server URL to a compatible remote MCP connector in ChatGPT or Claude.</p><CodeBlock label="MCP server URL" code="https://mcp.pixuno.xyz/mcp"/><ol className={styles.instructions}><li><strong>Add the connector</strong><p>Use the server URL in your client's remote MCP settings.</p></li><li><strong>Sign in to FlowPay</strong><p>Your client opens the authorization page. Sign in using your email code.</p></li><li><strong>Review and approve</strong><p>Approve the requested payment permissions. Your client receives scoped access through OAuth with PKCE.</p></li></ol><p>Review or disconnect approved apps in <a href="/developers">Developers</a>. Connector availability and setup depend on your client and plan.</p></section>
        <section id="api" className={styles.section}><div className={styles.sectionTitle}><span>06</span><h2>Build on the API</h2></div><p>Use merchant credentials or scoped OAuth tokens to create requests and read payment state. Receive lifecycle events through signed webhooks.</p><CodeBlock label="API base URL" code="https://api.pixuno.xyz"/><div className={styles.resources}><a href="https://github.com/gowithflowpay/flowpay/blob/main/flowpay/docs/cli.md"><strong>CLI reference &nearr;</strong><p>Installation and command usage.</p></a><a href="https://github.com/gowithflowpay/flowpay/blob/main/flowpay/apps/mcp/README.md"><strong>MCP reference &nearr;</strong><p>Remote OAuth and local stdio setup.</p></a></div></section>
        <footer className={styles.footer}><span>FlowPay developer documentation</span><a href="https://github.com/gowithflowpay/flowpay">View source &nearr;</a></footer>
      </main>
      <aside className={styles.toc}><span>ON THIS PAGE</span><a href="#quickstart">Install the CLI</a><a href="#account">Create an account</a><a href="#payments">Request a payment</a><a href="#agents">Agent workflows</a><a href="#mcp">MCP connections</a><a href="#api">API and reference</a><div><strong>Ready to build?</strong><p>Create your FlowPay account.</p><a href="/signup">Get started &rarr;</a></div></aside>
    </div>
  </div>;
}
